apiVersion: 1

contactPoints:
  - orgId: 1
    name: alert-webhook
    receivers:
      - uid: alert-webhook
        type: webhook
        settings:
          url: ${GRAFANA_ALERT_WEBHOOK_URL}
        disableResolveMessage: false